name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag name (default lcms2 version)'
        default: ''


jobs:
  build:
    uses: mpvkit/action/.github/workflows/build.yml@main
    secrets: inherit
    with:
      version: '${{ github.event.inputs.version }}'
      library: 'lcms2'